site_name: Learnings

nav:
  - Home: index.md

  - Linux:
      - SSH known_hosts: linux/known_hosts.md

  - Golang:
      - Reconciler basics: golang/reconciler-basics.md
      - Sync_waitgroup: golang/sync_waitgroup.md
      - module-addition: golang/module-addition.md

  - Others:
      - Helpfile: others/Helpfile.md
      - Git Commands: others/gitfilecommands.md
      - git-add-folder: others/git-add-folder.md
      - cursor-ssh: cursor/Navigate-to-directory.md
      - tls-explained: docs/others/tls-explaned.md

  - Kubernetes:
      - Documentation: k8s/k8sdocumentation.md
      - NSR: k8s/NSR.md
      - K8s-scheduling-docs:
          - overview: k8s-scheduling-docs/overview.md
          - node-affinity: k8s-scheduling-docs/node-affinity.md
          - nodeselector: k8s-scheduling-docs/nodeselector.md
          - taints: k8s-scheduling-docs/taints.md
          - tolerations: k8s-scheduling-docs/tolerations.md

  - Finance:
      - 3R-Strategy: finance/3R_Trading_Framework.md
      - Bulling-Engulfing: finance/bullish-engulfing.md
